# Generated by Django 4.2.7 on 2026-05-20 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Наприклад: DJI Phantom 4, DJI Mavic 3', max_length=100, verbose_name='Модель дрона')),
                ('serial_number', models.CharField(help_text='Унікальний серійний номер дрона', max_length=100, unique=True, verbose_name='Серійний номер')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('repair', 'На ремонті'), ('storage', 'На зберіганні')], default='active', max_length=20, verbose_name='Статус')),
                ('hours_flown', models.FloatField(default=0, help_text='Загальна кількість годин польотів', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Години льоту')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('max_flight_time', models.IntegerField(default=30, help_text='Максимальний час польоту у хвилинах', verbose_name='Макс. час польоту (хв)')),
                ('weight', models.FloatField(default=0, help_text='Вага дрона в грамах', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вага (г)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drones', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Дрон',
                'verbose_name_plural': 'Дрони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Планове обслуговування'), ('repair', 'Ремонт'), ('inspection', 'Експертиза'), ('upgrade', 'Модернізація')], max_length=20, verbose_name='Тип обслуговування')),
                ('description', models.TextField(help_text='Детальне описання того, що було зроблено', verbose_name='Опис робіт')),
                ('scheduled_date', models.DateTimeField(verbose_name='Запланована дата')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('status', models.CharField(choices=[('scheduled', 'Заплановане'), ('in_progress', 'У процесі'), ('completed', 'Завершене'), ('failed', 'Не виконане')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Вартість обслуговування', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вартість (грн)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='drones.drone', verbose_name='Дрон')),
                ('performed_by', models.ForeignKey(help_text='Технік хто виконав роботи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL, verbose_name='Виконано')),
            ],
            options={
                'verbose_name': 'Обслуговування',
                'verbose_name_plural': 'Обслуговування',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['drone', 'status'], name='drones_main_drone_i_cff22e_idx'), models.Index(fields=['scheduled_date'], name='drones_main_schedul_68b204_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата огляду')),
                ('inspector_name', models.CharField(max_length=100, verbose_name="Ім'я інспектора")),
                ('battery_health', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Здоров'я батареї (%)")),
                ('motor_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Попередження'), ('failed', 'Несправний')], default='ok', max_length=20, verbose_name='Стан моторів')),
                ('propeller_condition', models.CharField(choices=[('ok', 'OK'), ('warning', 'Попередження'), ('failed', 'Несправний')], default='ok', max_length=20, verbose_name='Стан пропелерів')),
                ('camera_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Попередження'), ('failed', 'Несправний')], default='ok', max_length=20, verbose_name='Стан камери')),
                ('gimbal_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('warning', 'Попередження'), ('failed', 'Несправний')], default='ok', max_length=20, verbose_name='Стан підвісу')),
                ('issues_found', models.TextField(blank=True, help_text='Детальний список виявлених проблем', verbose_name='Знайдені проблеми')),
                ('result', models.CharField(choices=[('passed', 'Пройшов огляд'), ('failed', 'Не пройшов'), ('warning', 'З попередженнями')], max_length=20, verbose_name='Результат огляду')),
                ('recommendations', models.TextField(blank=True, help_text='Рекомендовані дії', verbose_name='Рекомендації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='drones.drone', verbose_name='Дрон')),
            ],
            options={
                'verbose_name': 'Огляд',
                'verbose_name_plural': 'Огляди',
                'ordering': ['-inspection_date'],
                'indexes': [models.Index(fields=['drone', 'result'], name='drones_insp_drone_i_7e716c_idx'), models.Index(fields=['inspection_date'], name='drones_insp_inspect_a87471_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['serial_number'], name='drones_dron_serial__75848e_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['status'], name='drones_dron_status_9ef48e_idx'),
        ),
    ]
